ilios/lti-dashboard

- package-lock.json
- package.json
This is needed for ember-tooltips, but it isn't working quite right
probably due to some open PRs in that addon. Temporarily installing it
here solves an issue with tooltips not working on the calendar.
> Install ember-tether temporarily

- .travis.yml
This will make it much easier to test them in a real LTI container.
> Always deploy new master builds to staging

- package.json
- yarn.lock
With a better week at a glance route.
> Update ilios-common addon

- ember-cli-build.js
This is going to be the same and if we change it we still want all links
to point to the original
> Don't fingerprint the ilios-icon file

- package.json
This tag was already used and released.
> Fix version string

- package.json
- yarn.lock
> chore(package): update ilios-common to version 1.6.0

- package.json
> chore(package): update ilios-common to version 4.1.0

- package.json
- yarn.lock
> Greenkeeper/ember source 2.16.0

- package.json
- yarn.lock
> Greenkeeper/ember cli 2.16.2

- LICENSE.md
> added MIT license.

- package.json
- yarn.lock
> Greenkeeper/ilios common 9.0.0

- package.json
- yarn.lock
> chore(package): update ilios-common to version 12.1.0

- package.json
- yarn.lock
> Greenkeeper/ilios common 12.5.1

- package.json
- yarn.lock
> chore(package): update ilios-common to version 13.0.1

- package.json
- yarn.lock
> chore(package): update ilios-common to version 15.3.0

- package.json
- yarn.lock
> Greenkeeper/ember tether 1.0.0

- package.json
- yarn.lock
> Greenkeeper/ember fetch 5.0.1

- app/routes/login.js
- app/templates/login-error.hbs
This is cropping up in production for some reason so we need a better
error and a way to diagnose. Currently sending data to console for lack
of a better path.
> Improve error message on authentication error

- .npmrc
- package.json
> chore(package): update ilios-common to version 19.0.0

- app/templates/index.hbs
> pass new attributes to dashboard component.

- package-lock.json
- package.json
A few versions were tagged without updating the version info here, this
brings them back into alignment.
> Re-align version with tags

- package.json
> rm ember-fetch dependency, we're getting this from common.

- app/templates/index.hbs
- package-lock.json
- package.json
Updated the DashboardCalendar to angle bracket invocation and the new
API for this component.
> Update to common v34.0.0

- app/routes/index.js
This copies what this route looks like in production now that
pre-loading is happening in the controller.
> Replace dashboard route

- app/routes/application.js
- app/routes/login.js
- app/services/server-variables.js
- app/session-stores/application.js
Lots of individual issues were adding up to some trouble using the LTI in chrome and some recent FF versions. This cleans up each of these in a separate commit and should solve most problems.
> Fix Authentication

- config/ember-intl.js
- config/environment.js
- config/icons.js
fixes https://github.com/ilios/lti-dashboard/issues/683
> Deprecation warnings

- package-lock.json
- package.json
version 7 snuck into the master branch by accident, and it's not working.
therefore, this downgrade is necessary.
> downgrade ember-cli-postcss to latest v6.x release.

- app/routes/login.js
- config/dependency-lint.js
- config/icons.js
couple of smaller things, see commit messages.
> code cleanup

- app/routes/application.js
intl.locale returns an array of locales, we need to setup moment with
the first one.
> Set moment locale correctly

- package-lock.json
- package.json
reverts premature dependency update.
> revert to ilios-common v69.2.1

- package-lock.json
- package.json
> removes miragejs as dependency.

- .github/dependabot.yml
We get this from Ember CLI blueprints.
> Ignore Updates to Webpack
